"""increased image size

Revision ID: 3ab1023f950f
Revises: 24aefa4d2b30
Create Date: 2023-12-14 09:14:32.444749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab1023f950f'
down_revision = '24aefa4d2b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Image', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=45000),
               type_=sa.String(length=60000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Image', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=60000),
               type_=sa.VARCHAR(length=45000),
               existing_nullable=True)

    # ### end Alembic commands ###
